name: Deploy to GitHub Pages

on:
  push:
    branches: [solution-3]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          npm install
          npm install -g serve

      - name: Update next.config.js
        run: |
          echo "module.exports = { output: 'export', images: { unoptimized: true }, basePath: '/melvocal-coaching', assetPrefix: '/melvocal-coaching/' }" > next.config.js

      - name: Build
        run: |
          npm run build
          touch out/.nojekyll

      - name: Test Build
        run: |
          serve -s out -p 3000 &
          sleep 5
          curl -I http://localhost:3000

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: out
          clean-exclude: |
            .nojekyll