name: Deploy to GitHub Pages

on:
  push:
    branches: [solution-9]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install Dependencies
        run: |
          npm ci
          npm install -g @next/swc-linux-x64-gnu @next/swc-linux-x64-musl

      - name: Configure Next.js
        run: |
          cat > next.config.js << 'EOL'
          module.exports = {
            output: 'export',
            images: { unoptimized: true },
            basePath: '/melvocal-coaching',
            typescript: { ignoreBuildErrors: true },
            swcMinify: true
          }
          EOL

      - name: Build
        run: |
          npm run build
          touch out/.nojekyll
        env:
          NODE_ENV: production
          NEXT_IGNORE_TYPE_ERROR: true

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          folder: out
          clean: true
          single-commit: true
          git-config-name: github-actions[bot]
          git-config-email: github-actions[bot]@users.noreply.github.com
          commit-message: "Deploy Next.js site to GitHub Pages"